const COUNTRIES: Country[] = [
	{
		code: {alpha2: 'AF', alpha3: 'AFG'},
		name: {common: 'Afghanistan', native: 'افغانستان'},
		flagUrl: 'https://flagcdn.com/w320/af.png',
		population: 42647492,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Kabul'],
		currencies: 'AFN',
		languages: 'Pashto, Uzbek, Turkmen',
		borders: ['IRN', 'PAK', 'TKM', 'UZB', 'TJK', 'CHN'],
		domains: '.af',
	},
	{
		code: {alpha2: 'AX', alpha3: 'ALA'},
		name: {common: 'Åland Islands', native: 'Åland'},
		flagUrl: 'https://flagcdn.com/w320/ax.png',
		population: 28875,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Mariehamn'],
		currencies: 'EUR',
		languages: 'Swedish',
		domains: '.ax',
	},
	{
		code: {alpha2: 'AL', alpha3: 'ALB'},
		name: {common: 'Albania', native: 'Shqipëria'},
		flagUrl: 'https://flagcdn.com/w320/al.png',
		population: 2377128,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Tirana'],
		currencies: 'ALL',
		languages: 'Albanian',
		borders: ['MNE', 'GRC', 'MKD', 'UNK'],
		domains: '.al',
	},
	{
		code: {alpha2: 'DZ', alpha3: 'DZA'},
		name: {common: 'Algeria', native: 'الجزائر'},
		flagUrl: 'https://flagcdn.com/w320/dz.png',
		population: 46814308,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Algiers'],
		currencies: 'DZD',
		languages: 'Arabic',
		borders: ['TUN', 'LBY', 'NER', 'ESH', 'MRT', 'MLI', 'MAR'],
		domains: '.dz',
	},
	{
		code: {alpha2: 'AS', alpha3: 'ASM'},
		name: {common: 'American Samoa', native: 'American Samoa'},
		flagUrl: 'https://flagcdn.com/w320/as.png',
		population: 46765,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Pago Pago'],
		currencies: 'USD',
		languages: 'English, Samoan',
		domains: '.as',
	},
	{
		code: {alpha2: 'AD', alpha3: 'AND'},
		name: {common: 'Andorra', native: 'Andorra'},
		flagUrl: 'https://flagcdn.com/w320/ad.png',
		population: 81938,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Andorra la Vella'],
		currencies: 'EUR',
		languages: 'Catalan',
		borders: ['FRA', 'ESP'],
		domains: '.ad',
	},
	{
		code: {alpha2: 'AO', alpha3: 'AGO'},
		name: {common: 'Angola', native: 'Angola'},
		flagUrl: 'https://flagcdn.com/w320/ao.png',
		population: 37885849,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Luanda'],
		currencies: 'AOA',
		languages: 'Portuguese',
		borders: ['COG', 'COD', 'ZMB', 'NAM'],
		domains: '.ao',
	},
	{
		code: {alpha2: 'AI', alpha3: 'AIA'},
		name: {common: 'Anguilla', native: 'Anguilla'},
		flagUrl: 'https://flagcdn.com/w320/ai.png',
		population: 13452,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['The Valley'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.ai',
	},
	{
		code: {alpha2: 'AQ', alpha3: 'ATA'},
		name: {common: 'Antarctica', native: 'Antarctica'},
		flagUrl: 'https://flagcdn.com/w320/aq.png',
		population: 1000,
		region: 'Polar',
		subregion: 'Antarctica',
		languages: 'English, Russian',
		domains: '.aq',
	},
	{
		code: {alpha2: 'AG', alpha3: 'ATG'},
		name: {common: 'Antigua and Barbuda', native: 'Antigua and Barbuda'},
		flagUrl: 'https://flagcdn.com/w320/ag.png',
		population: 93772,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ["Saint John's"],
		currencies: 'XCD',
		languages: 'English',
		domains: '.ag',
	},
	{
		code: {alpha2: 'AR', alpha3: 'ARG'},
		name: {common: 'Argentina', native: 'Argentina'},
		flagUrl: 'https://flagcdn.com/w320/ar.png',
		population: 45696159,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Buenos Aires'],
		currencies: 'ARS',
		languages: 'Spanish, Guaraní',
		borders: ['BOL', 'BRA', 'CHL', 'PRY', 'URY'],
		domains: '.ar',
	},
	{
		code: {alpha2: 'AM', alpha3: 'ARM'},
		name: {common: 'Armenia', native: 'Հայաստան'},
		flagUrl: 'https://flagcdn.com/w320/am.png',
		population: 3033500,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Yerevan'],
		currencies: 'AMD',
		languages: 'Armenian',
		borders: ['AZE', 'GEO', 'IRN', 'TUR'],
		domains: '.am',
	},
	{
		code: {alpha2: 'AW', alpha3: 'ABW'},
		name: {common: 'Aruba', native: 'Aruba'},
		flagUrl: 'https://flagcdn.com/w320/aw.png',
		population: 107995,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Oranjestad'],
		currencies: 'AWG',
		languages: 'Dutch, (Eastern) Punjabi',
		domains: '.aw',
	},
	{
		code: {alpha2: 'AU', alpha3: 'AUS'},
		name: {common: 'Australia', native: 'Australia'},
		flagUrl: 'https://flagcdn.com/w320/au.png',
		population: 27196812,
		region: 'Oceania',
		subregion: 'Australia and New Zealand',
		capital: ['Canberra'],
		currencies: 'AUD',
		languages: 'English',
		domains: '.au',
	},
	{
		code: {alpha2: 'AT', alpha3: 'AUT'},
		name: {common: 'Austria', native: 'Österreich'},
		flagUrl: 'https://flagcdn.com/w320/at.png',
		population: 9177982,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Vienna'],
		currencies: 'EUR',
		languages: 'German',
		borders: ['CZE', 'DEU', 'HUN', 'ITA', 'LIE', 'SVK', 'SVN', 'CHE'],
		domains: '.at',
	},
	{
		code: {alpha2: 'AZ', alpha3: 'AZE'},
		name: {common: 'Azerbaijan', native: 'Azərbaycan'},
		flagUrl: 'https://flagcdn.com/w320/az.png',
		population: 10202830,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Baku'],
		currencies: 'AZN',
		languages: 'Azerbaijani',
		borders: ['ARM', 'GEO', 'IRN', 'RUS', 'TUR'],
		domains: '.az',
	},
	{
		code: {alpha2: 'BS', alpha3: 'BHS'},
		name: {common: 'Bahamas', native: 'Bahamas'},
		flagUrl: 'https://flagcdn.com/w320/bs.png',
		population: 401283,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Nassau'],
		currencies: 'BSD',
		languages: 'English',
		domains: '.bs',
	},
	{
		code: {alpha2: 'BH', alpha3: 'BHR'},
		name: {common: 'Bahrain', native: '‏البحرين'},
		flagUrl: 'https://flagcdn.com/w320/bh.png',
		population: 1588670,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Manama'],
		currencies: 'BHD',
		languages: 'Arabic',
		domains: '.bh',
	},
	{
		code: {alpha2: 'BD', alpha3: 'BGD'},
		name: {common: 'Bangladesh', native: 'Bangladesh'},
		flagUrl: 'https://flagcdn.com/w320/bd.png',
		population: 173562364,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Dhaka'],
		currencies: 'BDT',
		languages: 'Bengali',
		borders: ['MMR', 'IND'],
		domains: '.bd',
	},
	{
		code: {alpha2: 'BB', alpha3: 'BRB'},
		name: {common: 'Barbados', native: 'Barbados'},
		flagUrl: 'https://flagcdn.com/w320/bb.png',
		population: 282467,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Bridgetown'],
		currencies: 'BBD',
		languages: 'English',
		domains: '.bb',
	},
	{
		code: {alpha2: 'BY', alpha3: 'BLR'},
		name: {common: 'Belarus', native: 'Белару́сь'},
		flagUrl: 'https://flagcdn.com/w320/by.png',
		population: 9132629,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Minsk'],
		currencies: 'BYN, BYR',
		languages: 'Belarusian, Russian',
		borders: ['LVA', 'LTU', 'POL', 'RUS', 'UKR'],
		domains: '.by',
	},
	{
		code: {alpha2: 'BE', alpha3: 'BEL'},
		name: {common: 'Belgium', native: 'België'},
		flagUrl: 'https://flagcdn.com/w320/be.png',
		population: 11858610,
		region: 'Europe',
		subregion: 'Western Europe',
		capital: ['Brussels'],
		currencies: 'EUR',
		languages: 'Dutch, French, German',
		borders: ['FRA', 'DEU', 'LUX', 'NLD'],
		domains: '.be',
	},
	{
		code: {alpha2: 'BZ', alpha3: 'BLZ'},
		name: {common: 'Belize', native: 'Belize'},
		flagUrl: 'https://flagcdn.com/w320/bz.png',
		population: 417072,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['Belmopan'],
		currencies: 'BZD',
		languages: 'English, Spanish',
		borders: ['GTM', 'MEX'],
		domains: '.bz',
	},
	{
		code: {alpha2: 'BJ', alpha3: 'BEN'},
		name: {common: 'Benin', native: 'Bénin'},
		flagUrl: 'https://flagcdn.com/w320/bj.png',
		population: 14462724,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Porto-Novo'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['BFA', 'NER', 'NGA', 'TGO'],
		domains: '.bj',
	},
	{
		code: {alpha2: 'BM', alpha3: 'BMU'},
		name: {common: 'Bermuda', native: 'Bermuda'},
		flagUrl: 'https://flagcdn.com/w320/bm.png',
		population: 64636,
		region: 'Americas',
		subregion: 'Northern America',
		capital: ['Hamilton'],
		currencies: 'BMD',
		languages: 'English',
		domains: '.bm',
	},
	{
		code: {alpha2: 'BT', alpha3: 'BTN'},
		name: {common: 'Bhutan', native: 'ʼbrug-yul'},
		flagUrl: 'https://flagcdn.com/w320/bt.png',
		population: 791524,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Thimphu'],
		currencies: 'BTN, INR',
		languages: 'Dzongkha',
		borders: ['CHN', 'IND'],
		domains: '.bt',
	},
	{
		code: {alpha2: 'BO', alpha3: 'BOL'},
		name: {common: 'Bolivia (Plurinational State of)', native: 'Bolivia'},
		flagUrl: 'https://flagcdn.com/w320/bo.png',
		population: 12413315,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Sucre'],
		currencies: 'BOB',
		languages: 'Spanish, Aymara, Quechua',
		borders: ['ARG', 'BRA', 'CHL', 'PRY', 'PER'],
		domains: '.bo',
	},
	{
		code: {alpha2: 'BQ', alpha3: 'BES'},
		name: {common: 'Bonaire, Sint Eustatius and Saba', native: 'Bonaire'},
		flagUrl: 'https://flagcdn.com/w320/bq.png',
		population: 17408,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Kralendijk'],
		currencies: 'USD',
		languages: 'Dutch',
		domains: '.an, .nl',
	},
	{
		code: {alpha2: 'BA', alpha3: 'BIH'},
		name: {common: 'Bosnia and Herzegovina', native: 'Bosna i Hercegovina'},
		flagUrl: 'https://flagcdn.com/w320/ba.png',
		population: 3164253,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Sarajevo'],
		currencies: 'BAM',
		languages: 'Bosnian, Croatian, Serbian',
		borders: ['HRV', 'MNE', 'SRB'],
		domains: '.ba',
	},
	{
		code: {alpha2: 'BW', alpha3: 'BWA'},
		name: {common: 'Botswana', native: 'Botswana'},
		flagUrl: 'https://flagcdn.com/w320/bw.png',
		population: 2521139,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Gaborone'],
		currencies: 'BWP',
		languages: 'English, Tswana',
		borders: ['NAM', 'ZAF', 'ZMB', 'ZWE'],
		domains: '.bw',
	},
	{
		code: {alpha2: 'BV', alpha3: 'BVT'},
		name: {common: 'Bouvet Island', native: 'Bouvetøya'},
		flagUrl: 'https://flagcdn.com/w320/bv.png',
		region: 'Antarctic Ocean',
		subregion: 'South Antarctic Ocean',
		currencies: 'NOK',
		languages: 'Norwegian, Norwegian Bokmål, Norwegian Nynorsk',
		domains: '.bv',
	},
	{
		code: {alpha2: 'BR', alpha3: 'BRA'},
		name: {common: 'Brazil', native: 'Brasil'},
		flagUrl: 'https://flagcdn.com/w320/br.png',
		population: 211998573,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Brasília'],
		currencies: 'BRL',
		languages: 'Portuguese',
		borders: ['ARG', 'BOL', 'COL', 'FRA', 'GUF', 'GUY', 'PRY', 'PER', 'SUR', 'URY', 'VEN'],
		domains: '.br',
	},
	{
		code: {alpha2: 'IO', alpha3: 'IOT'},
		name: {common: 'British Indian Ocean Territory', native: 'British Indian Ocean Territory'},
		flagUrl: 'https://flagcdn.com/w320/io.png',
		population: 3000,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Diego Garcia'],
		currencies: 'USD',
		languages: 'English',
		domains: '.io',
	},
	{
		code: {alpha2: 'UM', alpha3: 'UMI'},
		name: {
			common: 'United States Minor Outlying Islands',
			native: 'United States Minor Outlying Islands',
		},
		flagUrl: 'https://flagcdn.com/w320/um.png',
		population: 300,
		region: 'Americas',
		subregion: 'Northern America',
		currencies: 'GBP',
		languages: 'English',
		domains: '.us',
	},
	{
		code: {alpha2: 'VG', alpha3: 'VGB'},
		name: {common: 'Virgin Islands (British)', native: 'British Virgin Islands'},
		flagUrl: 'https://flagcdn.com/w320/vg.png',
		population: 39471,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Road Town'],
		currencies: 'USD',
		languages: 'English',
		domains: '.vg',
	},
	{
		code: {alpha2: 'VI', alpha3: 'VIR'},
		name: {common: 'Virgin Islands (U.S.)', native: 'Virgin Islands of the United States'},
		flagUrl: 'https://flagcdn.com/w320/vi.png',
		population: 104377,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Charlotte Amalie'],
		currencies: 'USD',
		languages: 'English',
		domains: '.vi',
	},
	{
		code: {alpha2: 'BN', alpha3: 'BRN'},
		name: {common: 'Brunei Darussalam', native: 'Negara Brunei Darussalam'},
		flagUrl: 'https://flagcdn.com/w320/bn.png',
		population: 462721,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Bandar Seri Begawan'],
		currencies: 'BND, SGD',
		languages: 'Malay',
		borders: ['MYS'],
		domains: '.bn',
	},
	{
		code: {alpha2: 'BG', alpha3: 'BGR'},
		name: {common: 'Bulgaria', native: 'България'},
		flagUrl: 'https://flagcdn.com/w320/bg.png',
		population: 6441421,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Sofia'],
		currencies: 'BGN',
		languages: 'Bulgarian',
		borders: ['GRC', 'MKD', 'ROU', 'SRB', 'TUR'],
		domains: '.bg',
	},
	{
		code: {alpha2: 'BF', alpha3: 'BFA'},
		name: {common: 'Burkina Faso', native: 'Burkina Faso'},
		flagUrl: 'https://flagcdn.com/w320/bf.png',
		population: 23548781,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Ouagadougou'],
		currencies: 'XOF',
		languages: 'French, Fula',
		borders: ['BEN', 'CIV', 'GHA', 'MLI', 'NER', 'TGO'],
		domains: '.bf',
	},
	{
		code: {alpha2: 'BI', alpha3: 'BDI'},
		name: {common: 'Burundi', native: 'Burundi'},
		flagUrl: 'https://flagcdn.com/w320/bi.png',
		population: 14047786,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Gitega'],
		currencies: 'BIF',
		languages: 'French, Kirundi',
		borders: ['COD', 'RWA', 'TZA'],
		domains: '.bi',
	},
	{
		code: {alpha2: 'KH', alpha3: 'KHM'},
		name: {common: 'Cambodia', native: 'Kâmpŭchéa'},
		flagUrl: 'https://flagcdn.com/w320/kh.png',
		population: 17638801,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Phnom Penh'],
		currencies: 'KHR, USD',
		languages: 'Khmer',
		borders: ['LAO', 'THA', 'VNM'],
		domains: '.kh',
	},
	{
		code: {alpha2: 'CM', alpha3: 'CMR'},
		name: {common: 'Cameroon', native: 'Cameroon'},
		flagUrl: 'https://flagcdn.com/w320/cm.png',
		population: 29123744,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Yaoundé'],
		currencies: 'XAF',
		languages: 'English, French',
		borders: ['CAF', 'TCD', 'COG', 'GNQ', 'GAB', 'NGA'],
		domains: '.cm',
	},
	{
		code: {alpha2: 'CA', alpha3: 'CAN'},
		name: {common: 'Canada', native: 'Canada'},
		flagUrl: 'https://flagcdn.com/w320/ca.png',
		population: 41288599,
		region: 'Americas',
		subregion: 'Northern America',
		capital: ['Ottawa'],
		currencies: 'CAD',
		languages: 'English, French',
		borders: ['USA'],
		domains: '.ca',
	},
	{
		code: {alpha2: 'CV', alpha3: 'CPV'},
		name: {common: 'Cabo Verde', native: 'Cabo Verde'},
		flagUrl: 'https://flagcdn.com/w320/cv.png',
		population: 524877,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Praia'],
		currencies: 'CVE',
		languages: 'Portuguese',
		domains: '.cv',
	},
	{
		code: {alpha2: 'KY', alpha3: 'CYM'},
		name: {common: 'Cayman Islands', native: 'Cayman Islands'},
		flagUrl: 'https://flagcdn.com/w320/ky.png',
		population: 74457,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['George Town'],
		currencies: 'KYD',
		languages: 'English',
		domains: '.ky',
	},
	{
		code: {alpha2: 'CF', alpha3: 'CAF'},
		name: {common: 'Central African Republic', native: 'Ködörösêse tî Bêafrîka'},
		flagUrl: 'https://flagcdn.com/w320/cf.png',
		population: 5330690,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Bangui'],
		currencies: 'XAF',
		languages: 'French, Sango',
		borders: ['CMR', 'TCD', 'COD', 'COG', 'SSD', 'SDN'],
		domains: '.cf',
	},
	{
		code: {alpha2: 'TD', alpha3: 'TCD'},
		name: {common: 'Chad', native: 'Tchad'},
		flagUrl: 'https://flagcdn.com/w320/td.png',
		population: 20299123,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ["N'Djamena"],
		currencies: 'XAF',
		languages: 'French, Arabic',
		borders: ['CMR', 'CAF', 'LBY', 'NER', 'NGA', 'SDN'],
		domains: '.td',
	},
	{
		code: {alpha2: 'CL', alpha3: 'CHL'},
		name: {common: 'Chile', native: 'Chile'},
		flagUrl: 'https://flagcdn.com/w320/cl.png',
		population: 19764771,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Santiago'],
		currencies: 'CLP',
		languages: 'Spanish',
		borders: ['ARG', 'BOL', 'PER'],
		domains: '.cl',
	},
	{
		code: {alpha2: 'CN', alpha3: 'CHN'},
		name: {common: 'China', native: '中国'},
		flagUrl: 'https://flagcdn.com/w320/cn.png',
		population: 1408975000,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Beijing'],
		currencies: 'CNY',
		languages: 'Chinese',
		borders: [
			'AFG',
			'BTN',
			'MMR',
			'HKG',
			'IND',
			'KAZ',
			'PRK',
			'KGZ',
			'LAO',
			'MAC',
			'MNG',
			'PAK',
			'RUS',
			'TJK',
			'VNM',
			'NPL',
		],
		domains: '.cn',
	},
	{
		code: {alpha2: 'CX', alpha3: 'CXR'},
		name: {common: 'Christmas Island', native: 'Christmas Island'},
		flagUrl: 'https://flagcdn.com/w320/cx.png',
		population: 2072,
		region: 'Oceania',
		subregion: 'Australia and New Zealand',
		capital: ['Flying Fish Cove'],
		currencies: 'AUD',
		languages: 'English',
		domains: '.cx',
	},
	{
		code: {alpha2: 'CC', alpha3: 'CCK'},
		name: {common: 'Cocos (Keeling) Islands', native: 'Cocos (Keeling) Islands'},
		flagUrl: 'https://flagcdn.com/w320/cc.png',
		population: 550,
		region: 'Oceania',
		subregion: 'Australia and New Zealand',
		capital: ['West Island'],
		currencies: 'AUD',
		languages: 'English',
		domains: '.cc',
	},
	{
		code: {alpha2: 'CO', alpha3: 'COL'},
		name: {common: 'Colombia', native: 'Colombia'},
		flagUrl: 'https://flagcdn.com/w320/co.png',
		population: 52886363,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Bogotá'],
		currencies: 'COP',
		languages: 'Spanish',
		borders: ['BRA', 'ECU', 'PAN', 'PER', 'VEN'],
		domains: '.co',
	},
	{
		code: {alpha2: 'KM', alpha3: 'COM'},
		name: {common: 'Comoros', native: 'Komori'},
		flagUrl: 'https://flagcdn.com/w320/km.png',
		population: 866628,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Moroni'],
		currencies: 'KMF',
		languages: 'Arabic, French',
		domains: '.km',
	},
	{
		code: {alpha2: 'CG', alpha3: 'COG'},
		name: {common: 'Congo', native: 'République du Congo'},
		flagUrl: 'https://flagcdn.com/w320/cg.png',
		population: 6332961,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Brazzaville'],
		currencies: 'XAF',
		languages: 'French, Lingala',
		borders: ['AGO', 'CMR', 'CAF', 'COD', 'GAB'],
		domains: '.cg',
	},
	{
		code: {alpha2: 'CD', alpha3: 'COD'},
		name: {
			common: 'Congo (Democratic Republic of the)',
			native: 'République démocratique du Congo',
		},
		flagUrl: 'https://flagcdn.com/w320/cd.png',
		population: 109276265,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Kinshasa'],
		currencies: 'CDF',
		languages: 'French, Lingala, Kongo, Swahili, Luba-Katanga',
		borders: ['AGO', 'BDI', 'CAF', 'COG', 'RWA', 'SSD', 'TZA', 'UGA', 'ZMB'],
		domains: '.cd',
	},
	{
		code: {alpha2: 'CK', alpha3: 'COK'},
		name: {common: 'Cook Islands', native: 'Cook Islands'},
		flagUrl: 'https://flagcdn.com/w320/ck.png',
		population: 18100,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Avarua'],
		currencies: 'NZD, CKD',
		languages: 'English, Cook Islands Māori',
		domains: '.ck',
	},
	{
		code: {alpha2: 'CR', alpha3: 'CRI'},
		name: {common: 'Costa Rica', native: 'Costa Rica'},
		flagUrl: 'https://flagcdn.com/w320/cr.png',
		population: 5129910,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['San José'],
		currencies: 'CRC',
		languages: 'Spanish',
		borders: ['NIC', 'PAN'],
		domains: '.cr',
	},
	{
		code: {alpha2: 'HR', alpha3: 'HRV'},
		name: {common: 'Croatia', native: 'Hrvatska'},
		flagUrl: 'https://flagcdn.com/w320/hr.png',
		population: 3866200,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Zagreb'],
		currencies: 'EUR',
		languages: 'Croatian',
		borders: ['BIH', 'HUN', 'MNE', 'SRB', 'SVN'],
		domains: '.hr',
	},
	{
		code: {alpha2: 'CU', alpha3: 'CUB'},
		name: {common: 'Cuba', native: 'Cuba'},
		flagUrl: 'https://flagcdn.com/w320/cu.png',
		population: 10979783,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Havana'],
		currencies: 'CUC, CUP',
		languages: 'Spanish',
		domains: '.cu',
	},
	{
		code: {alpha2: 'CW', alpha3: 'CUW'},
		name: {common: 'Curaçao', native: 'Curaçao'},
		flagUrl: 'https://flagcdn.com/w320/cw.png',
		population: 155967,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Willemstad'],
		currencies: 'ANG',
		languages: 'Dutch, (Eastern) Punjabi, English',
		domains: '.cw',
	},
	{
		code: {alpha2: 'CY', alpha3: 'CYP'},
		name: {common: 'Cyprus', native: 'Κύπρος'},
		flagUrl: 'https://flagcdn.com/w320/cy.png',
		population: 1358282,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Nicosia'],
		currencies: 'EUR',
		languages: 'Greek (modern), Turkish, Armenian',
		borders: ['GBR'],
		domains: '.cy',
	},
	{
		code: {alpha2: 'CZ', alpha3: 'CZE'},
		name: {common: 'Czech Republic', native: 'Česká republika'},
		flagUrl: 'https://flagcdn.com/w320/cz.png',
		population: 10905028,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Prague'],
		currencies: 'CZK',
		languages: 'Czech, Slovak',
		domains: '.cz',
	},
	{
		code: {alpha2: 'DK', alpha3: 'DNK'},
		name: {common: 'Denmark', native: 'Danmark'},
		flagUrl: 'https://flagcdn.com/w320/dk.png',
		population: 5976992,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Copenhagen'],
		currencies: 'DKK',
		languages: 'Danish',
		borders: ['DEU'],
		domains: '.dk',
	},
	{
		code: {alpha2: 'DJ', alpha3: 'DJI'},
		name: {common: 'Djibouti', native: 'Djibouti'},
		flagUrl: 'https://flagcdn.com/w320/dj.png',
		population: 1168722,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Djibouti'],
		currencies: 'DJF',
		languages: 'French, Arabic',
		borders: ['ERI', 'ETH', 'SOM'],
		domains: '.dj',
	},
	{
		code: {alpha2: 'DM', alpha3: 'DMA'},
		name: {common: 'Dominica', native: 'Dominica'},
		flagUrl: 'https://flagcdn.com/w320/dm.png',
		population: 66205,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Roseau'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.dm',
	},
	{
		code: {alpha2: 'DO', alpha3: 'DOM'},
		name: {common: 'Dominican Republic', native: 'República Dominicana'},
		flagUrl: 'https://flagcdn.com/w320/do.png',
		population: 11427557,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Santo Domingo'],
		currencies: 'DOP',
		languages: 'Spanish',
		borders: ['HTI'],
		domains: '.do',
	},
	{
		code: {alpha2: 'EC', alpha3: 'ECU'},
		name: {common: 'Ecuador', native: 'Ecuador'},
		flagUrl: 'https://flagcdn.com/w320/ec.png',
		population: 18135478,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Quito'],
		currencies: 'USD',
		languages: 'Spanish',
		borders: ['COL', 'PER'],
		domains: '.ec',
	},
	{
		code: {alpha2: 'EG', alpha3: 'EGY'},
		name: {common: 'Egypt', native: 'مصر‎'},
		flagUrl: 'https://flagcdn.com/w320/eg.png',
		population: 116538258,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Cairo'],
		currencies: 'EGP',
		languages: 'Arabic',
		borders: ['ISR', 'LBY', 'SDN'],
		domains: '.eg',
	},
	{
		code: {alpha2: 'SV', alpha3: 'SLV'},
		name: {common: 'El Salvador', native: 'El Salvador'},
		flagUrl: 'https://flagcdn.com/w320/sv.png',
		population: 6338193,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['San Salvador'],
		currencies: 'USD',
		languages: 'Spanish',
		borders: ['GTM', 'HND'],
		domains: '.sv',
	},
	{
		code: {alpha2: 'GQ', alpha3: 'GNQ'},
		name: {common: 'Equatorial Guinea', native: 'Guinea Ecuatorial'},
		flagUrl: 'https://flagcdn.com/w320/gq.png',
		population: 1892516,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Malabo'],
		currencies: 'XAF',
		languages: 'Spanish, French, Portuguese, Fang',
		borders: ['CMR', 'GAB'],
		domains: '.gq',
	},
	{
		code: {alpha2: 'ER', alpha3: 'ERI'},
		name: {common: 'Eritrea', native: 'ኤርትራ'},
		flagUrl: 'https://flagcdn.com/w320/er.png',
		population: 3535603,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Asmara'],
		currencies: 'ERN',
		languages: 'Tigrinya, Arabic, English, Tigre, Kunama, Saho, Bilen, Nara, Afar',
		borders: ['DJI', 'ETH', 'SDN'],
		domains: '.er',
	},
	{
		code: {alpha2: 'EE', alpha3: 'EST'},
		name: {common: 'Estonia', native: 'Eesti'},
		flagUrl: 'https://flagcdn.com/w320/ee.png',
		population: 1372341,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Tallinn'],
		currencies: 'EUR',
		languages: 'Estonian',
		borders: ['LVA', 'RUS'],
		domains: '.ee',
	},
	{
		code: {alpha2: 'ET', alpha3: 'ETH'},
		name: {common: 'Ethiopia', native: 'ኢትዮጵያ'},
		flagUrl: 'https://flagcdn.com/w320/et.png',
		population: 132059767,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Addis Ababa'],
		currencies: 'ETB',
		languages: 'Amharic',
		borders: ['DJI', 'ERI', 'KEN', 'SOM', 'SSD', 'SDN'],
		domains: '.et',
	},
	{
		code: {alpha2: 'FK', alpha3: 'FLK'},
		name: {common: 'Falkland Islands (Malvinas)', native: 'Falkland Islands'},
		flagUrl: 'https://flagcdn.com/w320/fk.png',
		population: 2563,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Stanley'],
		currencies: 'FKP',
		languages: 'English',
		domains: '.fk',
	},
	{
		code: {alpha2: 'FO', alpha3: 'FRO'},
		name: {common: 'Faroe Islands', native: 'Føroyar'},
		flagUrl: 'https://flagcdn.com/w320/fo.png',
		population: 54681,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Tórshavn'],
		currencies: 'DKK, FOK',
		languages: 'Faroese',
		domains: '.fo',
	},
	{
		code: {alpha2: 'FJ', alpha3: 'FJI'},
		name: {common: 'Fiji', native: 'Fiji'},
		flagUrl: 'https://flagcdn.com/w320/fj.png',
		population: 928784,
		region: 'Oceania',
		subregion: 'Melanesia',
		capital: ['Suva'],
		currencies: 'FJD',
		languages: 'English, Fijian, Fiji Hindi, Rotuman',
		domains: '.fj',
	},
	{
		code: {alpha2: 'FI', alpha3: 'FIN'},
		name: {common: 'Finland', native: 'Suomi'},
		flagUrl: 'https://flagcdn.com/w320/fi.png',
		population: 5619911,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Helsinki'],
		currencies: 'EUR',
		languages: 'Finnish, Swedish',
		borders: ['NOR', 'SWE', 'RUS'],
		domains: '.fi',
	},
	{
		code: {alpha2: 'FR', alpha3: 'FRA'},
		name: {common: 'France', native: 'France'},
		flagUrl: 'https://flagcdn.com/w320/fr.png',
		population: 68551653,
		region: 'Europe',
		subregion: 'Western Europe',
		capital: ['Paris'],
		currencies: 'EUR',
		languages: 'French',
		borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
		domains: '.fr',
	},
	{
		code: {alpha2: 'GF', alpha3: 'GUF'},
		name: {common: 'French Guiana', native: 'Guyane française'},
		flagUrl: 'https://flagcdn.com/w320/gf.png',
		population: 254541,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Cayenne'],
		currencies: 'EUR',
		languages: 'French',
		borders: ['BRA', 'SUR'],
		domains: '.gf',
	},
	{
		code: {alpha2: 'PF', alpha3: 'PYF'},
		name: {common: 'French Polynesia', native: 'Polynésie française'},
		flagUrl: 'https://flagcdn.com/w320/pf.png',
		population: 281807,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Papeetē'],
		currencies: 'XPF',
		languages: 'French',
		domains: '.pf',
	},
	{
		code: {alpha2: 'TF', alpha3: 'ATF'},
		name: {
			common: 'French Southern Territories',
			native: 'Territoire des Terres australes et antarctiques françaises',
		},
		flagUrl: 'https://flagcdn.com/w320/tf.png',
		population: 140,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Port-aux-Français'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.tf',
	},
	{
		code: {alpha2: 'GA', alpha3: 'GAB'},
		name: {common: 'Gabon', native: 'Gabon'},
		flagUrl: 'https://flagcdn.com/w320/ga.png',
		population: 2538952,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Libreville'],
		currencies: 'XAF',
		languages: 'French',
		borders: ['CMR', 'COG', 'GNQ'],
		domains: '.ga',
	},
	{
		code: {alpha2: 'GM', alpha3: 'GMB'},
		name: {common: 'Gambia', native: 'Gambia'},
		flagUrl: 'https://flagcdn.com/w320/gm.png',
		population: 2759988,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Banjul'],
		currencies: 'GMD',
		languages: 'English',
		borders: ['SEN'],
		domains: '.gm',
	},
	{
		code: {alpha2: 'GE', alpha3: 'GEO'},
		name: {common: 'Georgia', native: 'საქართველო'},
		flagUrl: 'https://flagcdn.com/w320/ge.png',
		population: 3699557,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Tbilisi'],
		currencies: 'GEL',
		languages: 'Georgian',
		borders: ['ARM', 'AZE', 'RUS', 'TUR'],
		domains: '.ge',
	},
	{
		code: {alpha2: 'DE', alpha3: 'DEU'},
		name: {common: 'Germany', native: 'Deutschland'},
		flagUrl: 'https://flagcdn.com/w320/de.png',
		population: 83516593,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Berlin'],
		currencies: 'EUR',
		languages: 'German',
		borders: ['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'LUX', 'NLD', 'POL', 'CHE'],
		domains: '.de',
	},
	{
		code: {alpha2: 'GH', alpha3: 'GHA'},
		name: {common: 'Ghana', native: 'Ghana'},
		flagUrl: 'https://flagcdn.com/w320/gh.png',
		population: 34427414,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Accra'],
		currencies: 'GHS',
		languages: 'English',
		borders: ['BFA', 'CIV', 'TGO'],
		domains: '.gh',
	},
	{
		code: {alpha2: 'GI', alpha3: 'GIB'},
		name: {common: 'Gibraltar', native: 'Gibraltar'},
		flagUrl: 'https://flagcdn.com/w320/gi.png',
		population: 39329,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Gibraltar'],
		currencies: 'GIP',
		languages: 'English',
		borders: ['ESP'],
		domains: '.gi',
	},
	{
		code: {alpha2: 'GR', alpha3: 'GRC'},
		name: {common: 'Greece', native: 'Ελλάδα'},
		flagUrl: 'https://flagcdn.com/w320/gr.png',
		population: 10405134,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Athens'],
		currencies: 'EUR',
		languages: 'Greek (modern)',
		borders: ['ALB', 'BGR', 'TUR', 'MKD'],
		domains: '.gr',
	},
	{
		code: {alpha2: 'GL', alpha3: 'GRL'},
		name: {common: 'Greenland', native: 'Kalaallit Nunaat'},
		flagUrl: 'https://flagcdn.com/w320/gl.png',
		population: 56836,
		region: 'Americas',
		subregion: 'Northern America',
		capital: ['Nuuk'],
		currencies: 'DKK',
		languages: 'Kalaallisut',
		domains: '.gl',
	},
	{
		code: {alpha2: 'GD', alpha3: 'GRD'},
		name: {common: 'Grenada', native: 'Grenada'},
		flagUrl: 'https://flagcdn.com/w320/gd.png',
		population: 117207,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ["St. George's"],
		currencies: 'XCD',
		languages: 'English',
		domains: '.gd',
	},
	{
		code: {alpha2: 'GP', alpha3: 'GLP'},
		name: {common: 'Guadeloupe', native: 'Guadeloupe'},
		flagUrl: 'https://flagcdn.com/w320/gp.png',
		population: 400132,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Basse-Terre'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.gp',
	},
	{
		code: {alpha2: 'GU', alpha3: 'GUM'},
		name: {common: 'Guam', native: 'Guam'},
		flagUrl: 'https://flagcdn.com/w320/gu.png',
		population: 167777,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Hagåtña'],
		currencies: 'USD',
		languages: 'English, Chamorro, Spanish',
		domains: '.gu',
	},
	{
		code: {alpha2: 'GT', alpha3: 'GTM'},
		name: {common: 'Guatemala', native: 'Guatemala'},
		flagUrl: 'https://flagcdn.com/w320/gt.png',
		population: 18406359,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['Guatemala City'],
		currencies: 'GTQ',
		languages: 'Spanish',
		borders: ['BLZ', 'SLV', 'HND', 'MEX'],
		domains: '.gt',
	},
	{
		code: {alpha2: 'GG', alpha3: 'GGY'},
		name: {common: 'Guernsey', native: 'Guernsey'},
		flagUrl: 'https://flagcdn.com/w320/gg.png',
		population: 62999,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['St. Peter Port'],
		currencies: 'GBP, GGP',
		languages: 'English, French',
		domains: '.gg',
	},
	{
		code: {alpha2: 'GN', alpha3: 'GIN'},
		name: {common: 'Guinea', native: 'Guinée'},
		flagUrl: 'https://flagcdn.com/w320/gn.png',
		population: 14754785,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Conakry'],
		currencies: 'GNF',
		languages: 'French, Fula',
		borders: ['CIV', 'GNB', 'LBR', 'MLI', 'SEN', 'SLE'],
		domains: '.gn',
	},
	{
		code: {alpha2: 'GW', alpha3: 'GNB'},
		name: {common: 'Guinea-Bissau', native: 'Guiné-Bissau'},
		flagUrl: 'https://flagcdn.com/w320/gw.png',
		population: 2201352,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Bissau'],
		currencies: 'XOF',
		languages: 'Portuguese',
		borders: ['GIN', 'SEN'],
		domains: '.gw',
	},
	{
		code: {alpha2: 'GY', alpha3: 'GUY'},
		name: {common: 'Guyana', native: 'Guyana'},
		flagUrl: 'https://flagcdn.com/w320/gy.png',
		population: 831087,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Georgetown'],
		currencies: 'GYD',
		languages: 'English',
		borders: ['BRA', 'SUR', 'VEN'],
		domains: '.gy',
	},
	{
		code: {alpha2: 'HT', alpha3: 'HTI'},
		name: {common: 'Haiti', native: 'Haïti'},
		flagUrl: 'https://flagcdn.com/w320/ht.png',
		population: 11772557,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Port-au-Prince'],
		currencies: 'HTG',
		languages: 'French, Haitian',
		borders: ['DOM'],
		domains: '.ht',
	},
	{
		code: {alpha2: 'HM', alpha3: 'HMD'},
		name: {
			common: 'Heard Island and McDonald Islands',
			native: 'Heard Island and McDonald Islands',
		},
		flagUrl: 'https://flagcdn.com/w320/hm.png',
		region: 'Antarctic',
		subregion: 'Antarctic',
		currencies: 'AUD',
		languages: 'English',
		domains: '.hm, .aq',
	},
	{
		code: {alpha2: 'VA', alpha3: 'VAT'},
		name: {common: 'Vatican City', native: 'Status Civitatis Vaticanae'},
		flagUrl: 'https://flagcdn.com/w320/va.png',
		population: 451,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Vatican City'],
		currencies: 'EUR',
		languages: 'Latin, Italian, French, German',
		borders: ['ITA'],
		domains: '.va',
	},
	{
		code: {alpha2: 'HN', alpha3: 'HND'},
		name: {common: 'Honduras', native: 'Honduras'},
		flagUrl: 'https://flagcdn.com/w320/hn.png',
		population: 10825703,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['Tegucigalpa'],
		currencies: 'HNL',
		languages: 'Spanish',
		borders: ['GTM', 'SLV', 'NIC'],
		domains: '.hn',
	},
	{
		code: {alpha2: 'HU', alpha3: 'HUN'},
		name: {common: 'Hungary', native: 'Magyarország'},
		flagUrl: 'https://flagcdn.com/w320/hu.png',
		population: 9562065,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Budapest'],
		currencies: 'HUF',
		languages: 'Hungarian',
		borders: ['AUT', 'HRV', 'ROU', 'SRB', 'SVK', 'SVN', 'UKR'],
		domains: '.hu',
	},
	{
		code: {alpha2: 'HK', alpha3: 'HKG'},
		name: {common: 'Hong Kong', native: '香港'},
		flagUrl: 'https://flagcdn.com/w320/hk.png',
		population: 7524100,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['City of Victoria'],
		currencies: 'HKD',
		languages: 'English, Chinese',
		borders: ['CHN'],
		domains: '.hk',
	},
	{
		code: {alpha2: 'IS', alpha3: 'ISL'},
		name: {common: 'Iceland', native: 'Ísland'},
		flagUrl: 'https://flagcdn.com/w320/is.png',
		population: 386506,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Reykjavík'],
		currencies: 'ISK',
		languages: 'Icelandic',
		domains: '.is',
	},
	{
		code: {alpha2: 'IN', alpha3: 'IND'},
		name: {common: 'India', native: 'भारत'},
		flagUrl: 'https://flagcdn.com/w320/in.png',
		population: 1450935791,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['New Delhi'],
		currencies: 'INR',
		languages: 'Hindi, English',
		borders: ['AFG', 'BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK', 'LKA'],
		domains: '.in',
	},
	{
		code: {alpha2: 'ID', alpha3: 'IDN'},
		name: {common: 'Indonesia', native: 'Indonesia'},
		flagUrl: 'https://flagcdn.com/w320/id.png',
		population: 283487931,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Jakarta'],
		currencies: 'IDR',
		languages: 'Indonesian',
		borders: ['TLS', 'MYS', 'PNG'],
		domains: '.id',
	},
	{
		code: {alpha2: 'CI', alpha3: 'CIV'},
		name: {common: 'Ivory Coast', native: "Côte d'Ivoire"},
		flagUrl: 'https://flagcdn.com/w320/ci.png',
		population: 31934230,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Yamoussoukro'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['BFA', 'GHA', 'GIN', 'LBR', 'MLI'],
		domains: '.ci',
	},
	{
		code: {alpha2: 'IR', alpha3: 'IRN'},
		name: {common: 'Iran (Islamic Republic of)', native: 'ایران'},
		flagUrl: 'https://flagcdn.com/w320/ir.png',
		population: 91567738,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Tehran'],
		currencies: 'IRR',
		languages: 'Persian (Farsi)',
		borders: ['AFG', 'ARM', 'AZE', 'IRQ', 'PAK', 'TUR', 'TKM'],
		domains: '.ir',
	},
	{
		code: {alpha2: 'IQ', alpha3: 'IRQ'},
		name: {common: 'Iraq', native: 'العراق'},
		flagUrl: 'https://flagcdn.com/w320/iq.png',
		population: 46042015,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Baghdad'],
		currencies: 'IQD',
		languages: 'Arabic, Kurdish',
		borders: ['IRN', 'JOR', 'KWT', 'SAU', 'SYR', 'TUR'],
		domains: '.iq',
	},
	{
		code: {alpha2: 'IE', alpha3: 'IRL'},
		name: {common: 'Ireland', native: 'Éire'},
		flagUrl: 'https://flagcdn.com/w320/ie.png',
		population: 5395790,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Dublin'],
		currencies: 'EUR',
		languages: 'Irish, English',
		borders: ['GBR'],
		domains: '.ie',
	},
	{
		code: {alpha2: 'IM', alpha3: 'IMN'},
		name: {common: 'Isle of Man', native: 'Isle of Man'},
		flagUrl: 'https://flagcdn.com/w320/im.png',
		population: 84160,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Douglas'],
		currencies: 'GBP, IMP[G]',
		languages: 'English, Manx',
		domains: '.im',
	},
	{
		code: {alpha2: 'IL', alpha3: 'ISR'},
		name: {common: 'Israel', native: 'יִשְׂרָאֵל'},
		flagUrl: 'https://flagcdn.com/w320/il.png',
		population: 9974400,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Jerusalem'],
		currencies: 'ILS',
		languages: 'Hebrew (modern), Arabic',
		borders: ['EGY', 'JOR', 'LBN', 'SYR'],
		domains: '.il',
	},
	{
		code: {alpha2: 'IT', alpha3: 'ITA'},
		name: {common: 'Italy', native: 'Italia'},
		flagUrl: 'https://flagcdn.com/w320/it.png',
		population: 58952704,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Rome'],
		currencies: 'EUR',
		languages: 'Italian',
		borders: ['AUT', 'FRA', 'SMR', 'SVN', 'CHE', 'VAT'],
		domains: '.it',
	},
	{
		code: {alpha2: 'JM', alpha3: 'JAM'},
		name: {common: 'Jamaica', native: 'Jamaica'},
		flagUrl: 'https://flagcdn.com/w320/jm.png',
		population: 2839175,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Kingston'],
		currencies: 'JMD',
		languages: 'English',
		domains: '.jm',
	},
	{
		code: {alpha2: 'JP', alpha3: 'JPN'},
		name: {common: 'Japan', native: '日本'},
		flagUrl: 'https://flagcdn.com/w320/jp.png',
		population: 123975371,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Tokyo'],
		currencies: 'JPY',
		languages: 'Japanese',
		domains: '.jp',
	},
	{
		code: {alpha2: 'JE', alpha3: 'JEY'},
		name: {common: 'Jersey', native: 'Jersey'},
		flagUrl: 'https://flagcdn.com/w320/je.png',
		population: 100800,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Saint Helier'],
		currencies: 'GBP, JEP[G]',
		languages: 'English, French',
		domains: '.je',
	},
	{
		code: {alpha2: 'JO', alpha3: 'JOR'},
		name: {common: 'Jordan', native: 'الأردن'},
		flagUrl: 'https://flagcdn.com/w320/jo.png',
		population: 11552876,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Amman'],
		currencies: 'JOD',
		languages: 'Arabic',
		borders: ['IRQ', 'ISR', 'SAU', 'SYR'],
		domains: '.jo',
	},
	{
		code: {alpha2: 'KZ', alpha3: 'KAZ'},
		name: {common: 'Kazakhstan', native: 'Қазақстан'},
		flagUrl: 'https://flagcdn.com/w320/kz.png',
		population: 20592571,
		region: 'Asia',
		subregion: 'Central Asia',
		capital: ['Nur-Sultan'],
		currencies: 'KZT',
		languages: 'Kazakh, Russian',
		borders: ['CHN', 'KGZ', 'RUS', 'TKM', 'UZB'],
		domains: '.kz, .қаз',
	},
	{
		code: {alpha2: 'KE', alpha3: 'KEN'},
		name: {common: 'Kenya', native: 'Kenya'},
		flagUrl: 'https://flagcdn.com/w320/ke.png',
		population: 56432944,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Nairobi'],
		currencies: 'KES',
		languages: 'English, Swahili',
		borders: ['ETH', 'SOM', 'SSD', 'TZA', 'UGA'],
		domains: '.ke',
	},
	{
		code: {alpha2: 'KI', alpha3: 'KIR'},
		name: {common: 'Kiribati', native: 'Kiribati'},
		flagUrl: 'https://flagcdn.com/w320/ki.png',
		population: 134518,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['South Tarawa'],
		currencies: 'AUD, KID',
		languages: 'English',
		domains: '.ki',
	},
	{
		code: {alpha2: 'KW', alpha3: 'KWT'},
		name: {common: 'Kuwait', native: 'الكويت'},
		flagUrl: 'https://flagcdn.com/w320/kw.png',
		population: 4897263,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Kuwait City'],
		currencies: 'KWD',
		languages: 'Arabic',
		borders: ['IRQ', 'SAU'],
		domains: '.kw',
	},
	{
		code: {alpha2: 'KG', alpha3: 'KGZ'},
		name: {common: 'Kyrgyzstan', native: 'Кыргызстан'},
		flagUrl: 'https://flagcdn.com/w320/kg.png',
		population: 7221868,
		region: 'Asia',
		subregion: 'Central Asia',
		capital: ['Bishkek'],
		currencies: 'KGS',
		languages: 'Kyrgyz, Russian',
		borders: ['CHN', 'KAZ', 'TJK', 'UZB'],
		domains: '.kg',
	},
	{
		code: {alpha2: 'LA', alpha3: 'LAO'},
		name: {
			common: "Lao People's Democratic Republic",
			native: 'ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ',
		},
		flagUrl: 'https://flagcdn.com/w320/la.png',
		population: 7769819,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Vientiane'],
		currencies: 'LAK',
		languages: 'Lao',
		borders: ['MMR', 'KHM', 'CHN', 'THA', 'VNM'],
		domains: '.la',
	},
	{
		code: {alpha2: 'LV', alpha3: 'LVA'},
		name: {common: 'Latvia', native: 'Latvija'},
		flagUrl: 'https://flagcdn.com/w320/lv.png',
		population: 1866124,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Riga'],
		currencies: 'EUR',
		languages: 'Latvian',
		borders: ['BLR', 'EST', 'LTU', 'RUS'],
		domains: '.lv',
	},
	{
		code: {alpha2: 'LB', alpha3: 'LBN'},
		name: {common: 'Lebanon', native: 'لبنان'},
		flagUrl: 'https://flagcdn.com/w320/lb.png',
		population: 5805962,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Beirut'],
		currencies: 'LBP',
		languages: 'Arabic, French',
		borders: ['ISR', 'SYR'],
		domains: '.lb',
	},
	{
		code: {alpha2: 'LS', alpha3: 'LSO'},
		name: {common: 'Lesotho', native: 'Lesotho'},
		flagUrl: 'https://flagcdn.com/w320/ls.png',
		population: 2337423,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Maseru'],
		currencies: 'LSL, ZAR',
		languages: 'English, Southern Sotho',
		borders: ['ZAF'],
		domains: '.ls',
	},
	{
		code: {alpha2: 'LR', alpha3: 'LBR'},
		name: {common: 'Liberia', native: 'Liberia'},
		flagUrl: 'https://flagcdn.com/w320/lr.png',
		population: 5612817,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Monrovia'],
		currencies: 'LRD',
		languages: 'English',
		borders: ['GIN', 'CIV', 'SLE'],
		domains: '.lr',
	},
	{
		code: {alpha2: 'LY', alpha3: 'LBY'},
		name: {common: 'Libya', native: '‏ليبيا'},
		flagUrl: 'https://flagcdn.com/w320/ly.png',
		population: 7381023,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Tripoli'],
		currencies: 'LYD',
		languages: 'Arabic',
		borders: ['DZA', 'TCD', 'EGY', 'NER', 'SDN', 'TUN'],
		domains: '.ly',
	},
	{
		code: {alpha2: 'LI', alpha3: 'LIE'},
		name: {common: 'Liechtenstein', native: 'Liechtenstein'},
		flagUrl: 'https://flagcdn.com/w320/li.png',
		population: 40450,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Vaduz'],
		currencies: 'CHF',
		languages: 'German',
		borders: ['AUT', 'CHE'],
		domains: '.li',
	},
	{
		code: {alpha2: 'LT', alpha3: 'LTU'},
		name: {common: 'Lithuania', native: 'Lietuva'},
		flagUrl: 'https://flagcdn.com/w320/lt.png',
		population: 2888278,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Vilnius'],
		currencies: 'EUR',
		languages: 'Lithuanian',
		borders: ['BLR', 'LVA', 'POL', 'RUS'],
		domains: '.lt',
	},
	{
		code: {alpha2: 'LU', alpha3: 'LUX'},
		name: {common: 'Luxembourg', native: 'Lëtzebuerg'},
		flagUrl: 'https://flagcdn.com/w320/lu.png',
		population: 677012,
		region: 'Europe',
		subregion: 'Western Europe',
		capital: ['Luxembourg'],
		currencies: 'EUR',
		languages: 'French, German, Luxembourgish',
		borders: ['BEL', 'FRA', 'DEU'],
		domains: '.lu',
	},
	{
		code: {alpha2: 'MO', alpha3: 'MAC'},
		name: {common: 'Macao', native: '澳門'},
		flagUrl: 'https://flagcdn.com/w320/mo.png',
		population: 687000,
		region: 'Asia',
		subregion: 'Eastern Asia',
		currencies: 'MOP',
		languages: 'Chinese, Portuguese',
		borders: ['CHN'],
		domains: '.mo',
	},
	{
		code: {alpha2: 'MK', alpha3: 'MKD'},
		name: {common: 'North Macedonia', native: 'Македонија'},
		flagUrl: 'https://flagcdn.com/w320/mk.png',
		population: 1824359,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Skopje'],
		currencies: 'MKD',
		languages: 'Macedonian',
		borders: ['ALB', 'BGR', 'GRC', 'UNK', 'SRB'],
		domains: '.mk',
	},
	{
		code: {alpha2: 'MG', alpha3: 'MDG'},
		name: {common: 'Madagascar', native: 'Madagasikara'},
		flagUrl: 'https://flagcdn.com/w320/mg.png',
		population: 31964956,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Antananarivo'],
		currencies: 'MGA',
		languages: 'French, Malagasy',
		domains: '.mg',
	},
	{
		code: {alpha2: 'MW', alpha3: 'MWI'},
		name: {common: 'Malawi', native: 'Malawi'},
		flagUrl: 'https://flagcdn.com/w320/mw.png',
		population: 21655286,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Lilongwe'],
		currencies: 'MWK',
		languages: 'English, Chichewa',
		borders: ['MOZ', 'TZA', 'ZMB'],
		domains: '.mw',
	},
	{
		code: {alpha2: 'MY', alpha3: 'MYS'},
		name: {common: 'Malaysia', native: 'Malaysia'},
		flagUrl: 'https://flagcdn.com/w320/my.png',
		population: 35557673,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Kuala Lumpur'],
		currencies: 'MYR',
		languages: 'Malaysian',
		borders: ['BRN', 'IDN', 'THA'],
		domains: '.my',
	},
	{
		code: {alpha2: 'MV', alpha3: 'MDV'},
		name: {common: 'Maldives', native: 'Maldives'},
		flagUrl: 'https://flagcdn.com/w320/mv.png',
		population: 527799,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Malé'],
		currencies: 'MVR',
		languages: 'Divehi',
		domains: '.mv',
	},
	{
		code: {alpha2: 'ML', alpha3: 'MLI'},
		name: {common: 'Mali', native: 'Mali'},
		flagUrl: 'https://flagcdn.com/w320/ml.png',
		population: 24478595,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Bamako'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['DZA', 'BFA', 'GIN', 'CIV', 'MRT', 'NER', 'SEN'],
		domains: '.ml',
	},
	{
		code: {alpha2: 'MT', alpha3: 'MLT'},
		name: {common: 'Malta', native: 'Malta'},
		flagUrl: 'https://flagcdn.com/w320/mt.png',
		population: 568847,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Valletta'],
		currencies: 'EUR',
		languages: 'Maltese, English',
		domains: '.mt',
	},
	{
		code: {alpha2: 'MH', alpha3: 'MHL'},
		name: {common: 'Marshall Islands', native: 'M̧ajeļ'},
		flagUrl: 'https://flagcdn.com/w320/mh.png',
		population: 37548,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Majuro'],
		currencies: 'USD',
		languages: 'English, Marshallese',
		domains: '.mh',
	},
	{
		code: {alpha2: 'MQ', alpha3: 'MTQ'},
		name: {common: 'Martinique', native: 'Martinique'},
		flagUrl: 'https://flagcdn.com/w320/mq.png',
		population: 378243,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Fort-de-France'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.mq',
	},
	{
		code: {alpha2: 'MR', alpha3: 'MRT'},
		name: {common: 'Mauritania', native: 'موريتانيا'},
		flagUrl: 'https://flagcdn.com/w320/mr.png',
		population: 5169395,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Nouakchott'],
		currencies: 'MRO',
		languages: 'Arabic',
		borders: ['DZA', 'MLI', 'SEN', 'ESH'],
		domains: '.mr',
	},
	{
		code: {alpha2: 'MU', alpha3: 'MUS'},
		name: {common: 'Mauritius', native: 'Maurice'},
		flagUrl: 'https://flagcdn.com/w320/mu.png',
		population: 1245779,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Port Louis'],
		currencies: 'MUR',
		languages: 'English',
		domains: '.mu',
	},
	{
		code: {alpha2: 'YT', alpha3: 'MYT'},
		name: {common: 'Mayotte', native: 'Mayotte'},
		flagUrl: 'https://flagcdn.com/w320/yt.png',
		population: 226915,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Mamoudzou'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.yt',
	},
	{
		code: {alpha2: 'MX', alpha3: 'MEX'},
		name: {common: 'Mexico', native: 'México'},
		flagUrl: 'https://flagcdn.com/w320/mx.png',
		population: 130861007,
		region: 'Americas',
		subregion: 'North America',
		capital: ['Mexico City'],
		currencies: 'MXN',
		languages: 'Spanish',
		borders: ['BLZ', 'GTM', 'USA'],
		domains: '.mx',
	},
	{
		code: {alpha2: 'FM', alpha3: 'FSM'},
		name: {common: 'Micronesia (Federated States of)', native: 'Micronesia'},
		flagUrl: 'https://flagcdn.com/w320/fm.png',
		population: 113160,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Palikir'],
		currencies: 'USD',
		languages: 'English',
		domains: '.fm',
	},
	{
		code: {alpha2: 'MD', alpha3: 'MDA'},
		name: {common: 'Moldova (Republic of)', native: 'Moldova'},
		flagUrl: 'https://flagcdn.com/w320/md.png',
		population: 2402306,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Chișinău'],
		currencies: 'MDL',
		languages: 'Romanian',
		borders: ['ROU', 'UKR'],
		domains: '.md',
	},
	{
		code: {alpha2: 'MC', alpha3: 'MCO'},
		name: {common: 'Monaco', native: 'Monaco'},
		flagUrl: 'https://flagcdn.com/w320/mc.png',
		population: 38631,
		region: 'Europe',
		subregion: 'Western Europe',
		capital: ['Monaco'],
		currencies: 'EUR',
		languages: 'French',
		borders: ['FRA'],
		domains: '.mc',
	},
	{
		code: {alpha2: 'MN', alpha3: 'MNG'},
		name: {common: 'Mongolia', native: 'Монгол улс'},
		flagUrl: 'https://flagcdn.com/w320/mn.png',
		population: 3524788,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Ulan Bator'],
		currencies: 'MNT',
		languages: 'Mongolian',
		borders: ['CHN', 'RUS'],
		domains: '.mn',
	},
	{
		code: {alpha2: 'ME', alpha3: 'MNE'},
		name: {common: 'Montenegro', native: 'Црна Гора'},
		flagUrl: 'https://flagcdn.com/w320/me.png',
		population: 623525,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Podgorica'],
		currencies: 'EUR',
		languages: 'Serbian, Bosnian, Albanian, Croatian',
		borders: ['ALB', 'BIH', 'HRV', 'UNK', 'SRB'],
		domains: '.me',
	},
	{
		code: {alpha2: 'MS', alpha3: 'MSR'},
		name: {common: 'Montserrat', native: 'Montserrat'},
		flagUrl: 'https://flagcdn.com/w320/ms.png',
		population: 4922,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Plymouth'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.ms',
	},
	{
		code: {alpha2: 'MA', alpha3: 'MAR'},
		name: {common: 'Morocco', native: 'المغرب'},
		flagUrl: 'https://flagcdn.com/w320/ma.png',
		population: 38081173,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Rabat'],
		currencies: 'MAD',
		languages: 'Arabic',
		borders: ['DZA', 'ESH', 'ESP'],
		domains: '.ma',
	},
	{
		code: {alpha2: 'MZ', alpha3: 'MOZ'},
		name: {common: 'Mozambique', native: 'Moçambique'},
		flagUrl: 'https://flagcdn.com/w320/mz.png',
		population: 34631766,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Maputo'],
		currencies: 'MZN',
		languages: 'Portuguese',
		borders: ['MWI', 'ZAF', 'SWZ', 'TZA', 'ZMB', 'ZWE'],
		domains: '.mz',
	},
	{
		code: {alpha2: 'MM', alpha3: 'MMR'},
		name: {common: 'Myanmar', native: 'Myanma'},
		flagUrl: 'https://flagcdn.com/w320/mm.png',
		population: 54500091,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Naypyidaw'],
		currencies: 'MMK',
		languages: 'Burmese',
		borders: ['BGD', 'CHN', 'IND', 'LAO', 'THA'],
		domains: '.mm',
	},
	{
		code: {alpha2: 'NA', alpha3: 'NAM'},
		name: {common: 'Namibia', native: 'Namibia'},
		flagUrl: 'https://flagcdn.com/w320/na.png',
		population: 3030131,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Windhoek'],
		currencies: 'NAD, ZAR',
		languages: 'English, Afrikaans',
		borders: ['AGO', 'BWA', 'ZAF', 'ZMB'],
		domains: '.na',
	},
	{
		code: {alpha2: 'NR', alpha3: 'NRU'},
		name: {common: 'Nauru', native: 'Nauru'},
		flagUrl: 'https://flagcdn.com/w320/nr.png',
		population: 11947,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Yaren'],
		currencies: 'AUD',
		languages: 'English, Nauruan',
		domains: '.nr',
	},
	{
		code: {alpha2: 'NP', alpha3: 'NPL'},
		name: {common: 'Nepal', native: 'नेपाल'},
		flagUrl: 'https://flagcdn.com/w320/np.png',
		population: 29651054,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Kathmandu'],
		currencies: 'NPR',
		languages: 'Nepali',
		borders: ['CHN', 'IND'],
		domains: '.np',
	},
	{
		code: {alpha2: 'NL', alpha3: 'NLD'},
		name: {common: 'Netherlands', native: 'Nederland'},
		flagUrl: 'https://flagcdn.com/w320/nl.png',
		population: 17993485,
		region: 'Europe',
		subregion: 'Western Europe',
		capital: ['Amsterdam'],
		currencies: 'EUR',
		languages: 'Dutch',
		borders: ['BEL', 'DEU'],
		domains: '.nl',
	},
	{
		code: {alpha2: 'NC', alpha3: 'NCL'},
		name: {common: 'New Caledonia', native: 'Nouvelle-Calédonie'},
		flagUrl: 'https://flagcdn.com/w320/nc.png',
		population: 292639,
		region: 'Oceania',
		subregion: 'Melanesia',
		capital: ['Nouméa'],
		currencies: 'XPF',
		languages: 'French',
		domains: '.nc',
	},
	{
		code: {alpha2: 'NZ', alpha3: 'NZL'},
		name: {common: 'New Zealand', native: 'New Zealand'},
		flagUrl: 'https://flagcdn.com/w320/nz.png',
		population: 5287500,
		region: 'Oceania',
		subregion: 'Australia and New Zealand',
		capital: ['Wellington'],
		currencies: 'NZD',
		languages: 'English, Māori',
		domains: '.nz',
	},
	{
		code: {alpha2: 'NI', alpha3: 'NIC'},
		name: {common: 'Nicaragua', native: 'Nicaragua'},
		flagUrl: 'https://flagcdn.com/w320/ni.png',
		population: 6916140,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['Managua'],
		currencies: 'NIO',
		languages: 'Spanish',
		borders: ['CRI', 'HND'],
		domains: '.ni',
	},
	{
		code: {alpha2: 'NE', alpha3: 'NER'},
		name: {common: 'Niger', native: 'Niger'},
		flagUrl: 'https://flagcdn.com/w320/ne.png',
		population: 27032412,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Niamey'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['DZA', 'BEN', 'BFA', 'TCD', 'LBY', 'MLI', 'NGA'],
		domains: '.ne',
	},
	{
		code: {alpha2: 'NG', alpha3: 'NGA'},
		name: {common: 'Nigeria', native: 'Nigeria'},
		flagUrl: 'https://flagcdn.com/w320/ng.png',
		population: 232679478,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Abuja'],
		currencies: 'NGN',
		languages: 'English',
		borders: ['BEN', 'CMR', 'TCD', 'NER'],
		domains: '.ng',
	},
	{
		code: {alpha2: 'NU', alpha3: 'NIU'},
		name: {common: 'Niue', native: 'Niuē'},
		flagUrl: 'https://flagcdn.com/w320/nu.png',
		population: 1470,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Alofi'],
		currencies: 'NZD, NZD',
		languages: 'English',
		domains: '.nu',
	},
	{
		code: {alpha2: 'NF', alpha3: 'NFK'},
		name: {common: 'Norfolk Island', native: 'Norfolk Island'},
		flagUrl: 'https://flagcdn.com/w320/nf.png',
		population: 2302,
		region: 'Oceania',
		subregion: 'Australia and New Zealand',
		capital: ['Kingston'],
		currencies: 'AUD',
		languages: 'English',
		domains: '.nf',
	},
	{
		code: {alpha2: 'KP', alpha3: 'PRK'},
		name: {common: "Korea (Democratic People's Republic of)", native: '북한'},
		flagUrl: 'https://flagcdn.com/w320/kp.png',
		population: 26498823,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Pyongyang'],
		currencies: 'KPW',
		languages: 'Korean',
		borders: ['CHN', 'KOR', 'RUS'],
		domains: '.kp',
	},
	{
		code: {alpha2: 'MP', alpha3: 'MNP'},
		name: {common: 'Northern Mariana Islands', native: 'Northern Mariana Islands'},
		flagUrl: 'https://flagcdn.com/w320/mp.png',
		population: 44278,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Saipan'],
		currencies: 'USD',
		languages: 'English, Chamorro',
		domains: '.mp',
	},
	{
		code: {alpha2: 'NO', alpha3: 'NOR'},
		name: {common: 'Norway', native: 'Norge'},
		flagUrl: 'https://flagcdn.com/w320/no.png',
		population: 5572279,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Oslo'],
		currencies: 'NOK',
		languages: 'Norwegian, Norwegian Bokmål, Norwegian Nynorsk',
		borders: ['FIN', 'SWE', 'RUS'],
		domains: '.no',
	},
	{
		code: {alpha2: 'OM', alpha3: 'OMN'},
		name: {common: 'Oman', native: 'عمان'},
		flagUrl: 'https://flagcdn.com/w320/om.png',
		population: 5281538,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Muscat'],
		currencies: 'OMR',
		languages: 'Arabic',
		borders: ['SAU', 'ARE', 'YEM'],
		domains: '.om',
	},
	{
		code: {alpha2: 'PK', alpha3: 'PAK'},
		name: {common: 'Pakistan', native: 'Pakistan'},
		flagUrl: 'https://flagcdn.com/w320/pk.png',
		population: 251269164,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Islamabad'],
		currencies: 'PKR',
		languages: 'Urdu, English',
		borders: ['AFG', 'CHN', 'IND', 'IRN'],
		domains: '.pk',
	},
	{
		code: {alpha2: 'PW', alpha3: 'PLW'},
		name: {common: 'Palau', native: 'Palau'},
		flagUrl: 'https://flagcdn.com/w320/pw.png',
		population: 17695,
		region: 'Oceania',
		subregion: 'Micronesia',
		capital: ['Ngerulmud'],
		currencies: 'USD',
		languages: 'English',
		domains: '.pw',
	},
	{
		code: {alpha2: 'PS', alpha3: 'PSE'},
		name: {common: 'Palestine, State of', native: 'فلسطين'},
		flagUrl: 'https://flagcdn.com/w320/ps.png',
		population: 5289152,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Ramallah'],
		currencies: 'EGP, ILS, JOD',
		languages: 'Arabic',
		borders: ['ISR', 'EGY', 'JOR'],
		domains: '.ps',
	},
	{
		code: {alpha2: 'PA', alpha3: 'PAN'},
		name: {common: 'Panama', native: 'Panamá'},
		flagUrl: 'https://flagcdn.com/w320/pa.png',
		population: 4515577,
		region: 'Americas',
		subregion: 'Central America',
		capital: ['Panama City'],
		currencies: 'PAB, USD',
		languages: 'Spanish',
		borders: ['COL', 'CRI'],
		domains: '.pa',
	},
	{
		code: {alpha2: 'PG', alpha3: 'PNG'},
		name: {common: 'Papua New Guinea', native: 'Papua Niugini'},
		flagUrl: 'https://flagcdn.com/w320/pg.png',
		population: 10576502,
		region: 'Oceania',
		subregion: 'Melanesia',
		capital: ['Port Moresby'],
		currencies: 'PGK',
		languages: 'English',
		borders: ['IDN'],
		domains: '.pg',
	},
	{
		code: {alpha2: 'PY', alpha3: 'PRY'},
		name: {common: 'Paraguay', native: 'Paraguay'},
		flagUrl: 'https://flagcdn.com/w320/py.png',
		population: 6929153,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Asunción'],
		currencies: 'PYG',
		languages: 'Spanish, Guaraní',
		borders: ['ARG', 'BOL', 'BRA'],
		domains: '.py',
	},
	{
		code: {alpha2: 'PE', alpha3: 'PER'},
		name: {common: 'Peru', native: 'Perú'},
		flagUrl: 'https://flagcdn.com/w320/pe.png',
		population: 34217848,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Lima'],
		currencies: 'PEN',
		languages: 'Spanish',
		borders: ['BOL', 'BRA', 'CHL', 'COL', 'ECU'],
		domains: '.pe',
	},
	{
		code: {alpha2: 'PH', alpha3: 'PHL'},
		name: {common: 'Philippines', native: 'Pilipinas'},
		flagUrl: 'https://flagcdn.com/w320/ph.png',
		population: 115843670,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Manila'],
		currencies: 'PHP',
		languages: 'English',
		domains: '.ph',
	},
	{
		code: {alpha2: 'PN', alpha3: 'PCN'},
		name: {common: 'Pitcairn', native: 'Pitcairn Islands'},
		flagUrl: 'https://flagcdn.com/w320/pn.png',
		population: 56,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Adamstown'],
		currencies: 'NZD, PND',
		languages: 'English',
		domains: '.pn',
	},
	{
		code: {alpha2: 'PL', alpha3: 'POL'},
		name: {common: 'Poland', native: 'Polska'},
		flagUrl: 'https://flagcdn.com/w320/pl.png',
		population: 36559233,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Warsaw'],
		currencies: 'PLN',
		languages: 'Polish',
		borders: ['BLR', 'CZE', 'DEU', 'LTU', 'RUS', 'SVK', 'UKR'],
		domains: '.pl',
	},
	{
		code: {alpha2: 'PT', alpha3: 'PRT'},
		name: {common: 'Portugal', native: 'Portugal'},
		flagUrl: 'https://flagcdn.com/w320/pt.png',
		population: 10694681,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Lisbon'],
		currencies: 'EUR',
		languages: 'Portuguese',
		borders: ['ESP'],
		domains: '.pt',
	},
	{
		code: {alpha2: 'PR', alpha3: 'PRI'},
		name: {common: 'Puerto Rico', native: 'Puerto Rico'},
		flagUrl: 'https://flagcdn.com/w320/pr.png',
		population: 3203295,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['San Juan'],
		currencies: 'USD',
		languages: 'Spanish, English',
		domains: '.pr',
	},
	{
		code: {alpha2: 'QA', alpha3: 'QAT'},
		name: {common: 'Qatar', native: 'قطر'},
		flagUrl: 'https://flagcdn.com/w320/qa.png',
		population: 2857822,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Doha'],
		currencies: 'QAR',
		languages: 'Arabic',
		borders: ['SAU'],
		domains: '.qa',
	},
	{
		code: {alpha2: 'XK', alpha3: 'UNK'},
		name: {common: 'Republic of Kosovo', native: 'Republika e Kosovës'},
		flagUrl: 'https://flagcdn.com/w320/xk.png',
		population: 1594353,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Pristina'],
		currencies: 'EUR',
		languages: 'Albanian, Serbian',
		borders: ['ALB', 'MKD', 'MNE', 'SRB'],
		domains: '',
	},
	{
		code: {alpha2: 'RE', alpha3: 'REU'},
		name: {common: 'Réunion', native: 'La Réunion'},
		flagUrl: 'https://flagcdn.com/w320/re.png',
		population: 840974,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Saint-Denis'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.re',
	},
	{
		code: {alpha2: 'RO', alpha3: 'ROU'},
		name: {common: 'Romania', native: 'România'},
		flagUrl: 'https://flagcdn.com/w320/ro.png',
		population: 19051804,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Bucharest'],
		currencies: 'RON',
		languages: 'Romanian',
		borders: ['BGR', 'HUN', 'MDA', 'SRB', 'UKR'],
		domains: '.ro',
	},
	{
		code: {alpha2: 'RU', alpha3: 'RUS'},
		name: {common: 'Russian Federation', native: 'Россия'},
		flagUrl: 'https://flagcdn.com/w320/ru.png',
		population: 143533851,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Moscow'],
		currencies: 'RUB',
		languages: 'Russian',
		borders: [
			'AZE',
			'BLR',
			'CHN',
			'EST',
			'FIN',
			'GEO',
			'KAZ',
			'PRK',
			'LVA',
			'LTU',
			'MNG',
			'NOR',
			'POL',
			'UKR',
		],
		domains: '.ru',
	},
	{
		code: {alpha2: 'RW', alpha3: 'RWA'},
		name: {common: 'Rwanda', native: 'Rwanda'},
		flagUrl: 'https://flagcdn.com/w320/rw.png',
		population: 14256567,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Kigali'],
		currencies: 'RWF',
		languages: 'Kinyarwanda, English, French',
		borders: ['BDI', 'COD', 'TZA', 'UGA'],
		domains: '.rw',
	},
	{
		code: {alpha2: 'BL', alpha3: 'BLM'},
		name: {common: 'Saint Barthélemy', native: 'Saint-Barthélemy'},
		flagUrl: 'https://flagcdn.com/w320/bl.png',
		population: 9417,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Gustavia'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.bl',
	},
	{
		code: {alpha2: 'SH', alpha3: 'SHN'},
		name: {common: 'Saint Helena, Ascension and Tristan da Cunha', native: 'Saint Helena'},
		flagUrl: 'https://flagcdn.com/w320/sh.png',
		population: 4255,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Jamestown'],
		currencies: 'SHP',
		languages: 'English',
		domains: '.sh',
	},
	{
		code: {alpha2: 'KN', alpha3: 'KNA'},
		name: {common: 'Saint Kitts and Nevis', native: 'Saint Kitts and Nevis'},
		flagUrl: 'https://flagcdn.com/w320/kn.png',
		population: 46843,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Basseterre'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.kn',
	},
	{
		code: {alpha2: 'LC', alpha3: 'LCA'},
		name: {common: 'Saint Lucia', native: 'Saint Lucia'},
		flagUrl: 'https://flagcdn.com/w320/lc.png',
		population: 179744,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Castries'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.lc',
	},
	{
		code: {alpha2: 'MF', alpha3: 'MAF'},
		name: {common: 'Saint Martin (French part)', native: 'Saint-Martin'},
		flagUrl: 'https://flagcdn.com/w320/mf.png',
		population: 26129,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Marigot'],
		currencies: 'EUR',
		languages: 'English, French, Dutch',
		borders: ['SXM', 'NLD'],
		domains: '.mf, .fr, .gp',
	},
	{
		code: {alpha2: 'PM', alpha3: 'SPM'},
		name: {common: 'Saint Pierre and Miquelon', native: 'Saint-Pierre-et-Miquelon'},
		flagUrl: 'https://flagcdn.com/w320/pm.png',
		population: 6069,
		region: 'Americas',
		subregion: 'Northern America',
		capital: ['Saint-Pierre'],
		currencies: 'EUR',
		languages: 'French',
		domains: '.pm',
	},
	{
		code: {alpha2: 'VC', alpha3: 'VCT'},
		name: {
			common: 'Saint Vincent and the Grenadines',
			native: 'Saint Vincent and the Grenadines',
		},
		flagUrl: 'https://flagcdn.com/w320/vc.png',
		population: 100616,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Kingstown'],
		currencies: 'XCD',
		languages: 'English',
		domains: '.vc',
	},
	{
		code: {alpha2: 'WS', alpha3: 'WSM'},
		name: {common: 'Samoa', native: 'Samoa'},
		flagUrl: 'https://flagcdn.com/w320/ws.png',
		population: 218019,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Apia'],
		currencies: 'WST',
		languages: 'Samoan, English',
		domains: '.ws',
	},
	{
		code: {alpha2: 'SM', alpha3: 'SMR'},
		name: {common: 'San Marino', native: 'San Marino'},
		flagUrl: 'https://flagcdn.com/w320/sm.png',
		population: 33977,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['City of San Marino'],
		currencies: 'EUR',
		languages: 'Italian',
		borders: ['ITA'],
		domains: '.sm',
	},
	{
		code: {alpha2: 'ST', alpha3: 'STP'},
		name: {common: 'Sao Tome and Principe', native: 'São Tomé e Príncipe'},
		flagUrl: 'https://flagcdn.com/w320/st.png',
		population: 235536,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['São Tomé'],
		currencies: 'STD',
		languages: 'Portuguese',
		domains: '.st',
	},
	{
		code: {alpha2: 'SA', alpha3: 'SAU'},
		name: {common: 'Saudi Arabia', native: 'العربية السعودية'},
		flagUrl: 'https://flagcdn.com/w320/sa.png',
		population: 35300280,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Riyadh'],
		currencies: 'SAR',
		languages: 'Arabic',
		borders: ['IRQ', 'JOR', 'KWT', 'OMN', 'QAT', 'ARE', 'YEM'],
		domains: '.sa',
	},
	{
		code: {alpha2: 'SN', alpha3: 'SEN'},
		name: {common: 'Senegal', native: 'Sénégal'},
		flagUrl: 'https://flagcdn.com/w320/sn.png',
		population: 18501984,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Dakar'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['GMB', 'GIN', 'GNB', 'MLI', 'MRT'],
		domains: '.sn',
	},
	{
		code: {alpha2: 'RS', alpha3: 'SRB'},
		name: {common: 'Serbia', native: 'Србија'},
		flagUrl: 'https://flagcdn.com/w320/rs.png',
		population: 6586476,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Belgrade'],
		currencies: 'RSD',
		languages: 'Serbian',
		borders: ['BIH', 'BGR', 'HRV', 'HUN', 'UNK', 'MKD', 'MNE', 'ROU'],
		domains: '.rs',
	},
	{
		code: {alpha2: 'SC', alpha3: 'SYC'},
		name: {common: 'Seychelles', native: 'Seychelles'},
		flagUrl: 'https://flagcdn.com/w320/sc.png',
		population: 121354,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Victoria'],
		currencies: 'SCR',
		languages: 'French, English',
		domains: '.sc',
	},
	{
		code: {alpha2: 'SL', alpha3: 'SLE'},
		name: {common: 'Sierra Leone', native: 'Sierra Leone'},
		flagUrl: 'https://flagcdn.com/w320/sl.png',
		population: 8642022,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Freetown'],
		currencies: 'SLL',
		languages: 'English',
		borders: ['GIN', 'LBR'],
		domains: '.sl',
	},
	{
		code: {alpha2: 'SG', alpha3: 'SGP'},
		name: {common: 'Singapore', native: 'Singapore'},
		flagUrl: 'https://flagcdn.com/w320/sg.png',
		population: 6036860,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Singapore'],
		currencies: 'SGD',
		languages: 'English, Malay, Tamil, Chinese',
		domains: '.sg',
	},
	{
		code: {alpha2: 'SX', alpha3: 'SXM'},
		name: {common: 'Sint Maarten (Dutch part)', native: 'Sint Maarten'},
		flagUrl: 'https://flagcdn.com/w320/sx.png',
		population: 43350,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Philipsburg'],
		currencies: 'ANG',
		languages: 'Dutch, English',
		borders: ['MAF'],
		domains: '.sx',
	},
	{
		code: {alpha2: 'SK', alpha3: 'SVK'},
		name: {common: 'Slovakia', native: 'Slovensko'},
		flagUrl: 'https://flagcdn.com/w320/sk.png',
		population: 5422069,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Bratislava'],
		currencies: 'EUR',
		languages: 'Slovak',
		borders: ['AUT', 'CZE', 'HUN', 'POL', 'UKR'],
		domains: '.sk',
	},
	{
		code: {alpha2: 'SI', alpha3: 'SVN'},
		name: {common: 'Slovenia', native: 'Slovenija'},
		flagUrl: 'https://flagcdn.com/w320/si.png',
		population: 2127400,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Ljubljana'],
		currencies: 'EUR',
		languages: 'Slovene',
		borders: ['AUT', 'HRV', 'ITA', 'HUN'],
		domains: '.si',
	},
	{
		code: {alpha2: 'SB', alpha3: 'SLB'},
		name: {common: 'Solomon Islands', native: 'Solomon Islands'},
		flagUrl: 'https://flagcdn.com/w320/sb.png',
		population: 819198,
		region: 'Oceania',
		subregion: 'Melanesia',
		capital: ['Honiara'],
		currencies: 'SBD',
		languages: 'English',
		domains: '.sb',
	},
	{
		code: {alpha2: 'SO', alpha3: 'SOM'},
		name: {common: 'Somalia', native: 'Soomaaliya'},
		flagUrl: 'https://flagcdn.com/w320/so.png',
		population: 19009151,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Mogadishu'],
		currencies: 'SOS',
		languages: 'Somali, Arabic',
		borders: ['DJI', 'ETH', 'KEN'],
		domains: '.so',
	},
	{
		code: {alpha2: 'ZA', alpha3: 'ZAF'},
		name: {common: 'South Africa', native: 'South Africa'},
		flagUrl: 'https://flagcdn.com/w320/za.png',
		population: 64007187,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Pretoria'],
		currencies: 'ZAR',
		languages:
			'Afrikaans, English, Southern Ndebele, Southern Sotho, Swati, Tswana, Tsonga, Venda, Xhosa, Zulu',
		borders: ['BWA', 'LSO', 'MOZ', 'NAM', 'SWZ', 'ZWE'],
		domains: '.za',
	},
	{
		code: {alpha2: 'GS', alpha3: 'SGS'},
		name: {common: 'South Georgia and the South Sandwich Islands', native: 'South Georgia'},
		flagUrl: 'https://flagcdn.com/w320/gs.png',
		population: 30,
		region: 'Americas',
		subregion: 'South America',
		capital: ['King Edward Point'],
		currencies: 'FKP',
		languages: 'English',
		domains: '.gs',
	},
	{
		code: {alpha2: 'KR', alpha3: 'KOR'},
		name: {common: 'Korea (Republic of)', native: '대한민국'},
		flagUrl: 'https://flagcdn.com/w320/kr.png',
		population: 51751065,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Seoul'],
		currencies: 'KRW',
		languages: 'Korean',
		borders: ['PRK'],
		domains: '.kr',
	},
	{
		code: {alpha2: 'ES', alpha3: 'ESP'},
		name: {common: 'Spain', native: 'España'},
		flagUrl: 'https://flagcdn.com/w320/es.png',
		population: 48848840,
		region: 'Europe',
		subregion: 'Southern Europe',
		capital: ['Madrid'],
		currencies: 'EUR',
		languages: 'Spanish',
		borders: ['AND', 'FRA', 'GIB', 'PRT', 'MAR'],
		domains: '.es',
	},
	{
		code: {alpha2: 'LK', alpha3: 'LKA'},
		name: {common: 'Sri Lanka', native: 'śrī laṃkāva'},
		flagUrl: 'https://flagcdn.com/w320/lk.png',
		population: 21916000,
		region: 'Asia',
		subregion: 'Southern Asia',
		capital: ['Sri Jayawardenepura Kotte'],
		currencies: 'LKR',
		languages: 'Sinhalese, Tamil',
		borders: ['IND'],
		domains: '.lk',
	},
	{
		code: {alpha2: 'SD', alpha3: 'SDN'},
		name: {common: 'Sudan', native: 'السودان'},
		flagUrl: 'https://flagcdn.com/w320/sd.png',
		population: 50448963,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Khartoum'],
		currencies: 'SDG',
		languages: 'Arabic, English',
		borders: ['CAF', 'TCD', 'EGY', 'ERI', 'ETH', 'LBY', 'SSD'],
		domains: '.sd',
	},
	{
		code: {alpha2: 'SS', alpha3: 'SSD'},
		name: {common: 'South Sudan', native: 'South Sudan'},
		flagUrl: 'https://flagcdn.com/w320/ss.png',
		population: 11943408,
		region: 'Africa',
		subregion: 'Middle Africa',
		capital: ['Juba'],
		currencies: 'SSP',
		languages: 'English',
		borders: ['CAF', 'COD', 'ETH', 'KEN', 'SDN', 'UGA'],
		domains: '.ss',
	},
	{
		code: {alpha2: 'SR', alpha3: 'SUR'},
		name: {common: 'Suriname', native: 'Suriname'},
		flagUrl: 'https://flagcdn.com/w320/sr.png',
		population: 634431,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Paramaribo'],
		currencies: 'SRD',
		languages: 'Dutch',
		borders: ['BRA', 'FRA', 'GUF', 'GUY'],
		domains: '.sr',
	},
	{
		code: {alpha2: 'SJ', alpha3: 'SJM'},
		name: {common: 'Svalbard and Jan Mayen', native: 'Svalbard og Jan Mayen'},
		flagUrl: 'https://flagcdn.com/w320/sj.png',
		population: 2562,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Longyearbyen'],
		currencies: 'NOK',
		languages: 'Norwegian',
		domains: '.sj',
	},
	{
		code: {alpha2: 'SZ', alpha3: 'SWZ'},
		name: {common: 'Swaziland', native: 'Swaziland'},
		flagUrl: 'https://flagcdn.com/w320/sz.png',
		population: 1242822,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Mbabane'],
		currencies: 'SZL',
		languages: 'English, Swati',
		borders: ['MOZ', 'ZAF'],
		domains: '.sz',
	},
	{
		code: {alpha2: 'SE', alpha3: 'SWE'},
		name: {common: 'Sweden', native: 'Sverige'},
		flagUrl: 'https://flagcdn.com/w320/se.png',
		population: 10569709,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['Stockholm'],
		currencies: 'SEK',
		languages: 'Swedish',
		borders: ['FIN', 'NOR'],
		domains: '.se',
	},
	{
		code: {alpha2: 'CH', alpha3: 'CHE'},
		name: {common: 'Switzerland', native: 'Schweiz'},
		flagUrl: 'https://flagcdn.com/w320/ch.png',
		population: 9005582,
		region: 'Europe',
		subregion: 'Central Europe',
		capital: ['Bern'],
		currencies: 'CHF',
		languages: 'German, French, Italian, Romansh',
		borders: ['AUT', 'FRA', 'ITA', 'LIE', 'DEU'],
		domains: '.ch',
	},
	{
		code: {alpha2: 'SY', alpha3: 'SYR'},
		name: {common: 'Syrian Arab Republic', native: 'سوريا'},
		flagUrl: 'https://flagcdn.com/w320/sy.png',
		population: 24672760,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Damascus'],
		currencies: 'SYP',
		languages: 'Arabic',
		borders: ['IRQ', 'ISR', 'JOR', 'LBN', 'TUR'],
		domains: '.sy',
	},
	{
		code: {alpha2: 'TW', alpha3: 'TWN'},
		name: {common: 'Taiwan', native: '臺灣'},
		flagUrl: 'https://flagcdn.com/w320/tw.png',
		population: 23503349,
		region: 'Asia',
		subregion: 'Eastern Asia',
		capital: ['Taipei'],
		currencies: 'TWD',
		languages: 'Chinese',
		domains: '.tw',
	},
	{
		code: {alpha2: 'TJ', alpha3: 'TJK'},
		name: {common: 'Tajikistan', native: 'Тоҷикистон'},
		flagUrl: 'https://flagcdn.com/w320/tj.png',
		population: 10590927,
		region: 'Asia',
		subregion: 'Central Asia',
		capital: ['Dushanbe'],
		currencies: 'TJS',
		languages: 'Tajik, Russian',
		borders: ['AFG', 'CHN', 'KGZ', 'UZB'],
		domains: '.tj',
	},
	{
		code: {alpha2: 'TZ', alpha3: 'TZA'},
		name: {common: 'Tanzania, United Republic of', native: 'Tanzania'},
		flagUrl: 'https://flagcdn.com/w320/tz.png',
		population: 68560157,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Dodoma'],
		currencies: 'TZS',
		languages: 'Swahili, English',
		borders: ['BDI', 'COD', 'KEN', 'MWI', 'MOZ', 'RWA', 'UGA', 'ZMB'],
		domains: '.tz',
	},
	{
		code: {alpha2: 'TH', alpha3: 'THA'},
		name: {common: 'Thailand', native: 'ประเทศไทย'},
		flagUrl: 'https://flagcdn.com/w320/th.png',
		population: 71668011,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Bangkok'],
		currencies: 'THB',
		languages: 'Thai',
		borders: ['MMR', 'KHM', 'LAO', 'MYS'],
		domains: '.th',
	},
	{
		code: {alpha2: 'TL', alpha3: 'TLS'},
		name: {common: 'Timor-Leste', native: 'Timor-Leste'},
		flagUrl: 'https://flagcdn.com/w320/tl.png',
		population: 1400638,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Dili'],
		currencies: 'USD',
		languages: 'Portuguese',
		borders: ['IDN'],
		domains: '.tl',
	},
	{
		code: {alpha2: 'TG', alpha3: 'TGO'},
		name: {common: 'Togo', native: 'Togo'},
		flagUrl: 'https://flagcdn.com/w320/tg.png',
		population: 9515236,
		region: 'Africa',
		subregion: 'Western Africa',
		capital: ['Lomé'],
		currencies: 'XOF',
		languages: 'French',
		borders: ['BEN', 'BFA', 'GHA'],
		domains: '.tg',
	},
	{
		code: {alpha2: 'TK', alpha3: 'TKL'},
		name: {common: 'Tokelau', native: 'Tokelau'},
		flagUrl: 'https://flagcdn.com/w320/tk.png',
		population: 1411,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Fakaofo'],
		currencies: 'NZD',
		languages: 'English',
		domains: '.tk',
	},
	{
		code: {alpha2: 'TO', alpha3: 'TON'},
		name: {common: 'Tonga', native: 'Tonga'},
		flagUrl: 'https://flagcdn.com/w320/to.png',
		population: 104175,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ["Nuku'alofa"],
		currencies: 'TOP',
		languages: 'English, Tonga (Tonga Islands)',
		domains: '.to',
	},
	{
		code: {alpha2: 'TT', alpha3: 'TTO'},
		name: {common: 'Trinidad and Tobago', native: 'Trinidad and Tobago'},
		flagUrl: 'https://flagcdn.com/w320/tt.png',
		population: 1368333,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Port of Spain'],
		currencies: 'TTD',
		languages: 'English',
		domains: '.tt',
	},
	{
		code: {alpha2: 'TN', alpha3: 'TUN'},
		name: {common: 'Tunisia', native: 'تونس'},
		flagUrl: 'https://flagcdn.com/w320/tn.png',
		population: 12277109,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['Tunis'],
		currencies: 'TND',
		languages: 'Arabic',
		borders: ['DZA', 'LBY'],
		domains: '.tn',
	},
	{
		code: {alpha2: 'TR', alpha3: 'TUR'},
		name: {common: 'Turkey', native: 'Türkiye'},
		flagUrl: 'https://flagcdn.com/w320/tr.png',
		population: 85518661,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Ankara'],
		currencies: 'TRY',
		languages: 'Turkish',
		borders: ['ARM', 'AZE', 'BGR', 'GEO', 'GRC', 'IRN', 'IRQ', 'SYR'],
		domains: '.tr',
	},
	{
		code: {alpha2: 'TM', alpha3: 'TKM'},
		name: {common: 'Turkmenistan', native: 'Türkmenistan'},
		flagUrl: 'https://flagcdn.com/w320/tm.png',
		population: 7494498,
		region: 'Asia',
		subregion: 'Central Asia',
		capital: ['Ashgabat'],
		currencies: 'TMT',
		languages: 'Turkmen, Russian',
		borders: ['AFG', 'IRN', 'KAZ', 'UZB'],
		domains: '.tm',
	},
	{
		code: {alpha2: 'TC', alpha3: 'TCA'},
		name: {common: 'Turks and Caicos Islands', native: 'Turks and Caicos Islands'},
		flagUrl: 'https://flagcdn.com/w320/tc.png',
		population: 46535,
		region: 'Americas',
		subregion: 'Caribbean',
		capital: ['Cockburn Town'],
		currencies: 'USD',
		languages: 'English',
		domains: '.tc',
	},
	{
		code: {alpha2: 'TV', alpha3: 'TUV'},
		name: {common: 'Tuvalu', native: 'Tuvalu'},
		flagUrl: 'https://flagcdn.com/w320/tv.png',
		population: 9646,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Funafuti'],
		currencies: 'AUD, TVD[G]',
		languages: 'English',
		domains: '.tv',
	},
	{
		code: {alpha2: 'UG', alpha3: 'UGA'},
		name: {common: 'Uganda', native: 'Uganda'},
		flagUrl: 'https://flagcdn.com/w320/ug.png',
		population: 50015092,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Kampala'],
		currencies: 'UGX',
		languages: 'English, Swahili',
		borders: ['COD', 'KEN', 'RWA', 'SSD', 'TZA'],
		domains: '.ug',
	},
	{
		code: {alpha2: 'UA', alpha3: 'UKR'},
		name: {common: 'Ukraine', native: 'Україна'},
		flagUrl: 'https://flagcdn.com/w320/ua.png',
		population: 37860221,
		region: 'Europe',
		subregion: 'Eastern Europe',
		capital: ['Kyiv'],
		currencies: 'UAH',
		languages: 'Ukrainian',
		borders: ['BLR', 'HUN', 'MDA', 'POL', 'ROU', 'RUS', 'SVK'],
		domains: '.ua',
	},
	{
		code: {alpha2: 'AE', alpha3: 'ARE'},
		name: {common: 'United Arab Emirates', native: 'دولة الإمارات العربية المتحدة'},
		flagUrl: 'https://flagcdn.com/w320/ae.png',
		population: 10986400,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ['Abu Dhabi'],
		currencies: 'AED',
		languages: 'Arabic',
		borders: ['OMN', 'SAU'],
		domains: '.ae',
	},
	{
		code: {alpha2: 'GB', alpha3: 'GBR'},
		name: {
			common: 'United Kingdom of Great Britain and Northern Ireland',
			native: 'United Kingdom',
		},
		flagUrl: 'https://flagcdn.com/w320/gb.png',
		population: 69226000,
		region: 'Europe',
		subregion: 'Northern Europe',
		capital: ['London'],
		currencies: 'GBP',
		languages: 'English',
		borders: ['IRL'],
		domains: '.uk',
	},
	{
		code: {alpha2: 'US', alpha3: 'USA'},
		name: {common: 'United States of America', native: 'United States'},
		flagUrl: 'https://flagcdn.com/w320/us.png',
		population: 340110988,
		region: 'Americas',
		subregion: 'Northern America',
		capital: ['Washington, D.C.'],
		currencies: 'USD',
		languages: 'English',
		borders: ['CAN', 'MEX'],
		domains: '.us',
	},
	{
		code: {alpha2: 'UY', alpha3: 'URY'},
		name: {common: 'Uruguay', native: 'Uruguay'},
		flagUrl: 'https://flagcdn.com/w320/uy.png',
		population: 3386588,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Montevideo'],
		currencies: 'UYU',
		languages: 'Spanish',
		borders: ['ARG', 'BRA'],
		domains: '.uy',
	},
	{
		code: {alpha2: 'UZ', alpha3: 'UZB'},
		name: {common: 'Uzbekistan', native: 'O‘zbekiston'},
		flagUrl: 'https://flagcdn.com/w320/uz.png',
		population: 36361859,
		region: 'Asia',
		subregion: 'Central Asia',
		capital: ['Tashkent'],
		currencies: 'UZS',
		languages: 'Uzbek, Russian',
		borders: ['AFG', 'KAZ', 'KGZ', 'TJK', 'TKM'],
		domains: '.uz',
	},
	{
		code: {alpha2: 'VU', alpha3: 'VUT'},
		name: {common: 'Vanuatu', native: 'Vanuatu'},
		flagUrl: 'https://flagcdn.com/w320/vu.png',
		population: 327777,
		region: 'Oceania',
		subregion: 'Melanesia',
		capital: ['Port Vila'],
		currencies: 'VUV',
		languages: 'Bislama, English, French',
		domains: '.vu',
	},
	{
		code: {alpha2: 'VE', alpha3: 'VEN'},
		name: {common: 'Venezuela (Bolivarian Republic of)', native: 'Venezuela'},
		flagUrl: 'https://flagcdn.com/w320/ve.png',
		population: 28405543,
		region: 'Americas',
		subregion: 'South America',
		capital: ['Caracas'],
		currencies: 'VEF',
		languages: 'Spanish',
		borders: ['BRA', 'COL', 'GUY'],
		domains: '.ve',
	},
	{
		code: {alpha2: 'VN', alpha3: 'VNM'},
		name: {common: 'Vietnam', native: 'Việt Nam'},
		flagUrl: 'https://flagcdn.com/w320/vn.png',
		population: 100987686,
		region: 'Asia',
		subregion: 'South-Eastern Asia',
		capital: ['Hanoi'],
		currencies: 'VND',
		languages: 'Vietnamese',
		borders: ['KHM', 'CHN', 'LAO'],
		domains: '.vn',
	},
	{
		code: {alpha2: 'WF', alpha3: 'WLF'},
		name: {common: 'Wallis and Futuna', native: 'Wallis et Futuna'},
		flagUrl: 'https://flagcdn.com/w320/wf.png',
		population: 11750,
		region: 'Oceania',
		subregion: 'Polynesia',
		capital: ['Mata-Utu'],
		currencies: 'XPF',
		languages: 'French',
		domains: '.wf',
	},
	{
		code: {alpha2: 'EH', alpha3: 'ESH'},
		name: {common: 'Western Sahara', native: 'الصحراء الغربية'},
		flagUrl: 'https://flagcdn.com/w320/eh.png',
		population: 510713,
		region: 'Africa',
		subregion: 'Northern Africa',
		capital: ['El Aaiún'],
		currencies: 'MAD, DZD',
		languages: 'Spanish',
		borders: ['DZA', 'MRT', 'MAR'],
		domains: '.eh',
	},
	{
		code: {alpha2: 'YE', alpha3: 'YEM'},
		name: {common: 'Yemen', native: 'اليَمَن'},
		flagUrl: 'https://flagcdn.com/w320/ye.png',
		population: 40583164,
		region: 'Asia',
		subregion: 'Western Asia',
		capital: ["Sana'a"],
		currencies: 'YER',
		languages: 'Arabic',
		borders: ['OMN', 'SAU'],
		domains: '.ye',
	},
	{
		code: {alpha2: 'ZM', alpha3: 'ZMB'},
		name: {common: 'Zambia', native: 'Zambia'},
		flagUrl: 'https://flagcdn.com/w320/zm.png',
		population: 21314956,
		region: 'Africa',
		subregion: 'Eastern Africa',
		capital: ['Lusaka'],
		currencies: 'ZMW',
		languages: 'English',
		borders: ['AGO', 'BWA', 'COD', 'MWI', 'MOZ', 'NAM', 'TZA', 'ZWE'],
		domains: '.zm',
	},
	{
		code: {alpha2: 'ZW', alpha3: 'ZWE'},
		name: {common: 'Zimbabwe', native: 'Zimbabwe'},
		flagUrl: 'https://flagcdn.com/w320/zw.png',
		population: 16634373,
		region: 'Africa',
		subregion: 'Southern Africa',
		capital: ['Harare'],
		currencies: 'ZMW',
		languages: 'English, Shona, Northern Ndebele',
		borders: ['BWA', 'MOZ', 'ZAF', 'ZMB'],
		domains: '.zw',
	},
];

const COUNTRIES_COLLECTION: CountriesCollection = {};
COUNTRIES.forEach((country) => (COUNTRIES_COLLECTION[country.code.alpha3] = country));

export {COUNTRIES, COUNTRIES_COLLECTION};
